name: DeluxeCoinflip
version: '${version}'
main: fun.lewisdev.deluxecoinflip.DeluxeCoinflipPlugin
author: [ ItsLewizzz, ItzSave ]
api-version: 1.13

softdepend:
  - PlaceholderAPI
  - Vault
  - TokenEnchant
  - TokenManager

permissions:
  coinflip.admin:
    default: op