name: DeluxeCoinflip
version: '${version}'
main: net.zithium.deluxecoinflip.DeluxeCoinflipPlugin
authors: [ ItsLewizzz, ItzSave, ItsSimplyLeo ]
api-version: 1.19

softdepend:
  - PlaceholderAPI
  - Vault
  - TokenEnchant
  - TokenManager
  - EssentialsX

permissions:
  coinflip.admin:
    default: op
